[package]
name = "kiruna"
version = "0.1.0"
authors = ["Drew Crawford <drew@sealedabstract.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
sync = []
io_stream = []
# enable test_await fn
test = []
stream_with_dispatch = ["io_stream","dispatchr"]

[dependencies]
dispatchr = {path = "../dispatchr", optional=true}




