[workspace]

members = [
    "stream",
    "priority",
    "winbind",
]

[package]
name = "kiruna"
version = "0.1.0"
authors = ["Drew Crawford <drew@sealedabstract.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
sync = []
io_stream = ["stream"]
# enable test_await fn
test = []
# Various API to work with futures
futures = []
# API to join futures
join = []

[dependencies]
stream = {path = "stream", optional=true}
priority = {path = "priority" }