[package]
name = "kiruna_tpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
priority = {path = "../priority"}
once_cell = "~1"
#libc = "~0"
crossbeam-channel = "~0"