[package]
name = "spawn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
priority = {path = "../priority"}

[target.'cfg(target_os="windows")'.dependencies.windows]
version = "~0"
features = []