on: [push]
jobs:
  mac:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: cargo test --features=all --all
      - run: cargo doc --features=all
  win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo test --features=all --all
      - run: cargo doc --features=all